### ISSUE TITLE
SAY IT BACK

### ISSUE THREAD

**Issue by munsy** [VedalAI/swarm-control#1]
COME ON, MAN

**Comment by ayaaop** [comment]
not resolved yet

**Comment by munsy** [comment]
agreed, reopening because this is a pressing issue and should not be ignored

**Comment by Alexejhero** [comment]
nice spam 

![](https://cdn.7tv.app/emote/6235309d961be6c9af3d2d1f/4x.png)

**Comment by Alexejhero** [comment]
SMH you forget that even though this is vedal's repo he doesnt check the issues
