### ISSUE TITLE
[EBS] Add redeem moderation

### ISSUE THREAD

**Issue by Alexejhero** [VedalAI/swarm-control#13]
Redeems should be moderated somehow, specifically ones which have a text argument.

(Moderation queue needed, this seems like a lot of work)

**Comment by Alexejhero** [comment]
This can be implemented on either the front end or the back end

**Comment by Alexejhero** [comment]
! This is required if we have free text fields.

**Comment by Vedal987** [comment]
Only have moderation for redeems with text fields.

**Comment by Vedal987** [comment]
Just send request to twitch automod.
