### ISSUE TITLE
(Discussion) Planning or something like that

### ISSUE THREAD

**Issue by Zyrenth** [VedalAI/swarm-control#2]
It would be great to have a plan for what we want to add and use for this repo before we start doing anything so here we can discuss it and also make a plan.
  
I can definitely help with designing and coding the UI or the backend. (idk if the backend is gonna be in a separate repo or how will this be)

**Comment by Alexejhero** [comment]
> discuss it and also make a plan

brother the deadline is like late wednesday / early thursday 
there is no discussion or plan to be had just do whatever

im working on backend separately, so dont worry about that.

**Comment by Zyrenth** [comment]
> brother the deadline is like late wednesday / early thursday 
> there is no discussion or plan to be had just do whatever

lol mb I tend to overcomplicate things for whatever reason

> im working on backend separately, so dont worry about that.

okay cool

**Comment by Alexejhero** [comment]
actually the backend is in the repo now as well so feel free to contribute

**Comment by Zyrenth** [comment]
well then i might check it out but for now i'm focused on the UI

**Comment by Alexejhero** [comment]
well you better hurry
