### ISSUE TITLE
[FE] Investigate if we can prevent mouse inputs from going down to twitch player&window

### ISSUE THREAD

**Issue by Alexejhero** [VedalAI/swarm-control#24]
Double clicking in the extension can minimize/maximize the twitch player, and also scrolling is a bit jarring if not in fullscreen because it scrolls the whole window once you reach an end.

maybe this can be fixed?

**Comment by Vedal987** [comment]
0cb5d4caabe13a27d515c120fde1a57775837f57

**Comment by Vedal987** [comment]
Scroll chaining still isn't fixed

**Comment by Vedal987** [comment]
Fixed in f3cc4efa175ea02801140c62107c4b3ad29ba5bc
Scrolling can still occur if there's no scollbar available but the user shouldn't be scrolling.
