### ISSUE TITLE
[FE] bits display animation clearly wasn't made with mobile in mind :)

### ISSUE THREAD

**Issue by Alexejhero** [VedalAI/swarm-control#29]
![Screenshot_2024-06-10-04-51-26-360_tv twitch android app](https://github.com/VedalAI/swarm-control/assets/32238504/e88caf9a-982f-4848-b89b-f65c099236f7)

**Comment by Alexejhero** [comment]
you can't really hover over elements can you?

you have to hold to see the price which is bad ux

**Comment by Vedal987** [comment]
Fixed in b3e64aef7aa82b150d4dd8f79df7edb11aa41d0e
