### ISSUE TITLE
[FE] Open the error or successful payment modal back up if the transaction ended and the user dismissed the processing modal.

### ISSUE THREAD

**Issue by Zyrenth** [VedalAI/swarm-control#32]
just an idea.

**Comment by Alexejhero** [comment]
Processing modal should not be dismissible except if it times out

**Comment by Alexejhero** [comment]
And if it does time out, I don't think there's any way that a transaction is still ongoing

**Comment by Alexejhero** [comment]
Modal is only dismissible if 30 seconds pass during the twitch process, but if the user can click the button that means they already closed the twitch popup
