### ISSUE TITLE
[FE] Disclaimer for moderated redeems

### ISSUE THREAD

**Issue by Govorunb** [VedalAI/swarm-control#35]
For redeems that have to go through a moderation queue, there should be some sort of disclaimer that the redeem may get rejected.

Alternatively, put a general catch-all disclaimer (in onboarding) that redeems are best effort and aren't fully guaranteed to show on stream or whatever.

**Comment by Alexejhero** [comment]
I imagine the moderation queue thing will be a part of the prepurchase flow

**Comment by Alexejhero** [comment]
So we can just change the text saying this might take a bit

(yes i will sit there the entire stream and watch for new messages)

![https://cdn.7tv.app/emote/618573ef4ea2f24e50097c62/4x.webp](https://cdn.7tv.app/emote/618573ef4ea2f24e50097c62/4x.webp)

**Comment by LeBogoo** [comment]
what about sending it through neuros filter?

**Comment by Zyrenth** [comment]
> what about sending it through neuros filter?

it's pretty much bypassable because of people can just combine text and numbers and special characters which would just pass on neuro's filter (since its mostly just a list of words AFAIK)

**Comment by Govorunb** [comment]
twitch has an endpoint for checking arbitrary text through automod, it would be much easier (obtain api token and make 1 call) to put it through them
