### ISSUE TITLE
Notify frontend of game state

### ISSUE THREAD

**Issue by Govorunb** [VedalAI/swarm-control#45]
- Socket up/down should enable/disable all redeems
- (optional) "In-game" bool (e.g. "Send Text" is available in main menu but "Spawn X" is not)

**Comment by Alexejhero** [comment]
@govorunb Didn't we already talk about this being unnecessary?

Because we can only verify prepurchases, no one is stopping someone from creating a prepurchase then spending 10 minutes buying bits and then accepting, which defeats the purpose of enabling/disabling all redeems like this.

**Comment by Alexejhero** [comment]
So at that point you might as well let them redeem at any point and they can be queued on the EBS

**Comment by Govorunb** [comment]
it's a ux issue, there's no point showing redeems when you can't redeem them
(now that prepurchase actually fails without a socket connection since 7cc7ba944be08f5add9c65e096e4f837fd5c7f06)

**Comment by Govorunb** [comment]
holding a cart for 10 minutes will not be the average user experience i assure you

**Comment by Alexejhero** [comment]
if this is UX then fair, but we can't rely on this in any way. there still needs to be queuing on the ebs

**Comment by Govorunb** [comment]
implemented in 22db61c5112d64af4dc547e6415240752437cc21 and 8c41c1095dc297965d8914b95724a2ea7846b58b
queueing redeems that failed to send is in, but actually (re-)sending from the queue is todo
