### ISSUE TITLE
Split up the config (if needed)

### ISSUE THREAD

**Issue by Govorunb** [VedalAI/swarm-control#46]
```
ebs-1          | [Mt: Encountered HTTP status code 422: Unprocessable Entity
ebs-1          |
ebs-1          | URL: extensions/pubsub
ebs-1          | Method: POST
ebs-1          | Body:
ebs-1          | {"error":"Unprocessable Entity","status":422,"message":"The message is too large."}] {
ebs-1          |   _statusCode: 422,
ebs-1          |   _url: 'extensions/pubsub',
ebs-1          |   _method: 'POST',
ebs-1          |   _body: '{"error":"Unprocessable Entity","status":422,"message":"The message is too large."}'
ebs-1          | }
```

**Comment by Alexejhero** [comment]
I wonder whose fault this is

**Comment by Alexejhero** [comment]
Good thing we discovered this now rather than running into it later

**Comment by Alexejhero** [comment]
Surely we dont need to do this and we can just reduce the size of the strings right

**Comment by Vedal987** [comment]
https://101arrowz.github.io/fflate/

**Comment by Vedal987** [comment]
Added compression with gzip, which should *hopefully* mean this isn't an issue again. Compressed data is sent as a Latin-1 encoded string, which is not very efficient but I'm not sure there is a better option in this case.

cb69ee3925ef0715895295047cf31c8e76732296
