### ISSUE TITLE
Respond with transaction call with result that comes from game

### ISSUE THREAD

**Issue by Alexejhero** [VedalAI/swarm-control#47]
If a redeem fails, tell the user.

We can add this without any issues since we have no manual moderation.

We should also modify the frontend a bit to display the response body in the modal just like it does if there's an error.

**Comment by Vedal987** [comment]
5bfa44971a194e496f4be801b8b973e79d96f452 Frontend will now show response body in the modal.

**Comment by Govorunb** [comment]
EBS now [awaits](https://github.com/VedalAI/swarm-control/commit/22db61c5112d64af4dc547e6415240752437cc21?diff=unified&w=1#diff-8fdb5a49f32e5e913584e9a704f5601cc6d772592dc5e01416624c04d25c4f35R247) the result from the game ([with a 10s timeout](https://github.com/VedalAI/swarm-control/commit/22db61c5112d64af4dc547e6415240752437cc21?diff=unified&w=1#diff-a01d382761aa0c6aaf28c1ae669a64bc4e9c7f2f7a8aef092ffc47c7ca9aeac8R117))
