### ISSUE TITLE
[LOGGER] Stop logging to Discord

### ISSUE THREAD

**Issue by Govorunb** [VedalAI/swarm-control#48]
![image](https://github.com/VedalAI/swarm-control/assets/3830522/c138d459-da89-4e94-8e62-f2a8cc5c0dc4)

You can easily hit Discord's ratelimit, and a single 429 crashes the whole logger

The logger is supposed to be the most resilient piece of this whole setup so this is an unacceptable risk

**Comment by Alexejhero** [comment]
Skill issue, just don't trigger any logs
