### ISSUE TITLE
[FE] Vector3

### ISSUE THREAD

**Issue by Govorunb** [VedalAI/swarm-control#49]
![image](https://github.com/VedalAI/swarm-control/assets/3830522/7a2d13ed-b07a-4821-8d89-db2c743b208f)

https://github.com/VedalAI/swarm-control/blob/d148f89692eb82513bb7b868aa90749f2dfb1b33/frontend/www/src/modules/modal.ts#L203

**Comment by Alexejhero** [comment]
how

**Comment by Govorunb** [comment]
Every time you click "Redeem" it adds 3 elements to the array, so if the form isn't valid on first click you're doomed

**Comment by Alexejhero** [comment]
Then we just grab the last 3 elements on the ebs

**Comment by Zyrenth** [comment]
> Every time you click "Redeem" it adds 3 elements to the array, so if the form isn't valid on first click you're doomed

But how do you even press the redeem button multiple times? Because when you open the modal the cart is set back to the default values which erases the previous arguments. (And error and success modals just close the modal.)

**Comment by Zyrenth** [comment]
NVM I thought we actually disabled the redeem button when the form is invalid but it's just visually disabled and it's still clickable.
