### ISSUE TITLE
[FE] Closing the success modal by clicking outside of it doesnt dismiss it

### ISSUE THREAD

**Issue by Alexejhero** [VedalAI/swarm-control#50]
This might also happen with the error modal, not sure.

But basically when you open the modal back up it still has that message in it

**Comment by Zyrenth** [comment]
It only happens to success modals because the error and processing modals get hidden when the main modal opens.

![image](https://github.com/VedalAI/swarm-control/assets/71086259/c510e3d4-0ebf-4aa8-9b61-7a16b5d12ac2)
